# Generated by Django 3.1.5 on 2021-01-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=50)),
                ('d_desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_email', models.EmailField(max_length=254, unique=True)),
                ('l_password', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField()),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('r_desc', models.CharField(max_length=100)),
                ('d_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='First.doctor')),
                ('l_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='First.login')),
            ],
            options={
                'db_table': 'rate',
            },
        ),
    ]
