# Generated by Django 3.1.6 on 2021-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='First/static/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
